### ISSUE TITLE
Is the example table at Task 2-2 in "2019 Coding Task for Back-end and Development " correct?

### ISSUE THREAD

**Issue by naoki-kishi** [pfnet/intern-coding-tasks#5]
## What

I think the example table at Task 2-2 in [Preferred Networks Intern Screening 2019 Coding Task for Back-end Development](https://github.com/pfnet/intern-coding-tasks/blob/master/2019/backend/Problem-en.pdf) is not correct.

`Executing Point` is the sum of `Remaining Point`, so `Executing Point` at 00:00:06 would be 5, not 6.

### origin table
| timestamp | JobID - Task No ( Remain Point ) || Executing Point |
|:-----------|:------------|:-----|:--------|
|00:00:01 | 1-1(5) | | 5 |
|00:00:02 | 1-1(4) | | 4 |
|00:00:03 | 1-1(3) | 2-1(3) | 6 |
|00:00:04 | 1-1(2) | 2-1(2) | 4 |
|00:00:05 | 1-1(1) | 2-1(1) | 2 |
|00:00:06 | |  2-2(5) | **6** |
|00:00:07 | 1-2(6) | 2-2(4) | 10 |
|...|...|...|...|

### fixed table
| timestamp | JobID - Task No ( Remain Point ) || Executing Point |
|:-----------|:------------|:-----|:--------|
|00:00:01 | 1-1(5) | | 5 |
|00:00:02 | 1-1(4) | | 4 |
|00:00:03 | 1-1(3) | 2-1(3) | 6 |
|00:00:04 | 1-1(2) | 2-1(2) | 4 |
|00:00:05 | 1-1(1) | 2-1(1) | 2 |
|00:00:06 | | 2-2(5) | **5** |
|00:00:07 | 1-2(6) | 2-2(4) | 10 |
|...|...|...|...|

**Comment by ir5** [comment]
Thank you for pointing out the mistake! Indeed, it seems that we accidentally uploaded the "old version" of the statement. I fixed the statement by #6.

**Comment by ir5** [comment]
I will close this issue.

**Comment by naoki-kishi** [comment]
Thank you for fix!
